version: '3.4'

services:
  sql:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    environment:
      - SA_PASSWORD=admin123!
      - ACCEPT_EULA="Y"
    ports: 
      - 1433:1433 
    volumes:
      - ./database/sql/data:/var/opt/mssql/data
      - ./database/sql/log:/var/opt/mssql/log
      - ./database/sql/secrets:/var/opt/mssql/secrets