version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: admin123!
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    volumes:
      - ./database/sql:/var/opt/mssql