version: '3.4'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: admin123!
      MSSQL_PID: 'Express'
    ports:
      - '1433:1433'
    command: /bin/sh /usr/src/app/entrypoint.sh
    volumes:
      - ./database/sql:/var/opt/mssql
      - ./init.sql:/usr/src/app/init.sql
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh